server:
  port: 10080
  tomcat:
    uri-encoding: UTF-8
logging:
  config: classpath:log4j2.xml
spring:
  datasource:
    datasource-common:
      name: datasource-common
      url: jdbc:mysql://rm-2ze180j4fln454i5s4o.mysql.rds.aliyuncs.com:3306/markonly?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: Liuyujiao3080701
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-idle: 5
      max-wait: 10000
      min-idle: 1
      initial-size: 3
      max-active: 600
    datasource-user:
      name: datasource-user
      url: jdbc:mysql://rm-2ze180j4fln454i5s4o.mysql.rds.aliyuncs.com:3306/markonly?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: Liuyujiao3080701
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-idle: 5
      max-wait: 10000
      min-idle: 1
      initial-size: 3
      max-active: 600
  application:
    name: common-server
  http:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  aop: 
    auto: true
  redis:
    database: 1
    host: 39.105.106.238
    port: 6379
    password: 123456
    timeout: 5000
    pool:
      max-active: 300
      max-wait: 100000
      max-idle: 150
      min-idle: 100
eureka:
  instance:
    lease-renewal-interval-in-seconds: 1      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
    instance-enabled-onit: true
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:10090/eureka/
    enabled: true
ribbon:
  # 配置首台服务器重试1次
  MaxAutoRetries: 0
  # 配置其他服务器重试两次
  MaxAutoRetriesNextServer: 1
  # 连接超时时间
  ConnectTimeout: 500
  # 请求处理时间
  ReadTimeout: 2000
  # 每个操作都开启重试机制
  OkToRetryOnAllOperations: true
feign:
  hystrix:
    enabled: false
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true
